### ISSUE TITLE
Rewrite tiny code snippet

### ISSUE THREAD

**Issue by intns** [projectPiki/pikmin2#123]
https://github.com/projectPiki/pikmin2/blob/a6e89e8b3679e5de880fe2baed613ba2837d8075/src/plugProjectYamashitaU/enemyBase.cpp#L430

`if (!(enemy->m_health <= 0.0f) && (enemy->isAlive())) {`

to

`if (enemy->m_health > 0.0f && enemy->isAlive()) {` <-- makes more sense!

**Comment by HeartPiece44** [comment]
Unfortunately this doesn't match - codegen requires the `cror eq, lt, eq` instruction and this doesn't generate it.
