### ISSUE TITLE
Replace HW_REG usage with approriate macros/inlines.

### ISSUE THREAD

**Issue by HeartPiece44** [projectPiki/pikmin2#155]
Places in the repo using the `HW_REG()` macro should instead use the appropriate wrapper (either a `GXWGFifo` inline for `0xCC008XXX`s, or something from `Dolphin/hw_regs.h` for other `0xCC00XXXX`s) for better clarity/specificity.

**Comment by EpochFlame** [comment]
I'll go through the files still using them this month and figure out what needs to be done.
