### ISSUE TITLE
Are these two lines in the wrong order?

### ISSUE THREAD

**Issue by atm959** [projectPiki/pikmin2#174]
In /src/plugProjectYamashitaU/lifeGaugeMgr.cpp, I noticed something odd: the if statements on line 152 and 153 seem like they may possibly be in the wrong order. With the code there, it seems like the life gauge would turn red at 20% health, and would never turn yellow, as the outer if statement is executed if the health is less than 20%, and the inner if statement would execute if the health is less than 50%, setting the health to red, but its else statement would never run, which would set the health to yellow.

https://github.com/projectPiki/pikmin2/blob/30f1a5aebef56dc19a6d012027524548fbd2c3fd/src/plugProjectYamashitaU/lifeGaugeMgr.cpp#L152
https://github.com/projectPiki/pikmin2/blob/30f1a5aebef56dc19a6d012027524548fbd2c3fd/src/plugProjectYamashitaU/lifeGaugeMgr.cpp#L153

**Comment by intns** [comment]
Thank you for your concern! I regret to inform you that the file isn't finished or matched *yet*, you are completely right in that it is wrong.
