### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by itsaidendipier-ro** [projectPiki/pikmin2#28]
Hi, I'm new to hacking Pikmin 2. I was told that I would need to hack the main.dol file in sys for some stuff. It doesn't let me hack it so I was linked this website. I read your readme. I do have a hard time understanding instructions and these instructions as well. What I want to do is make it where I can open the main.dol and I think I have to use something here. I was wondering if you could start me fresh with an easily explained way to download, what to do and where to put these files and how I can open the main.dol? Thanks.

**Comment by EpochFlame** [comment]
The main.dol is a compiled executable, and cannot be "opened" with an editor like a .txt file. you may achieve limited success with hex editing, but our project builds an entirely new dol from the PowerPC assembly and decompiled C/C++ source sode files in the asm and src folders, respectively.

Respectfully, doing DOL edits while being new to the modding scene will likely be overwhelming, so I suggest getting advice from the nice folks in [Hocotate Hacker](https://discord.gg/G7Pgkdh) and starting off with the vanilla DOL, and trying out a few of the research-2 gecko codes to see if they do anything interesting.

Best of luck in your modding endeavors.
