### ISSUE TITLE
static libraries

### ISSUE THREAD

**Issue by EpochFlame** [projectPiki/pikmin2#9]
We should make sysBootup into a static library, since it's complete. This will show us how to make the others into static libraries.

**Comment by intns** [comment]
At some point this should be addressed, can't remember at the moment if there are instances of using different pragmas based on the folder being worked on. But if there is, source code may be cleaned up by this.

As it stands, still not a priority 9 months later

**Comment by EpochFlame** [comment]
Mostly differentiates the sub-libraries of Dolphin.a. The other libraries appear to use the same settings.
